[routers]
r1 ansible_host=192.168.100.11
r2 ansible_host=192.168.100.12
r3 ansible_host=192.168.100.13

[routers:vars]
ansible_user=admin
ansible_password=PasswordSegura123!
ansible_network_os=ios
ansible_connection=network_cli
ansible_host_key_checking=False
ansible_paramiko_host_key_checking=False
ansible_paramiko_missing_host_key_policy=AutoAddPolicy
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o KexAlgorithms=+diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1 -o Ciphers=+aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc'
