---
- name: Desplegar Topologia IPSec/GRE/OSPF VPN Full-Mesh
  hosts: routers
  gather_facts: no
  collections:
    - cisco.ios
  vars_files:
    - group_vars/all/vault.yml

  roles:
    - base_interfaces
    - ipsec_crypto
    - gre_tunnels
    - ospf_routing
