name: Pipeline CI-CD NetDevOps Pipo (Cisco IOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pruebas:
    name: Validar sintaxis de Ansible
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Validar Sintaxis
        run: ansible-playbook --syntax-check site.yml -i inventory.ini --vault-password-file "${{ github.workspace }}/.vault_pass"

  despliegue_simulado:
    name: Simular Despliegue en Routers Cisco
    needs: pruebas
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Dry-Run con Vault
        run: ansible-playbook -i inventory.ini site.yml --check --vault-password-file "${{ github.workspace }}/.vault_pass"
